### ISSUE TITLE
No documentation on how to extract parent from HTTP request headers

### ISSUE THREAD

**Issue by bpmason1** [sile/rustracing#2]
A common use case from tracing is to follow requests across multiple applications by adding relevant information about the trace to the HTTP headers in the request.  How do I extract those headers with this library (specifically, I'm using hyper) and create a child span across application boundaries?

**Comment by bpmason1** [comment]
I can unpack the headers into a HashMap<Strig, String> if that's any easier to handle.

**Comment by sile** [comment]
I added an example of the simplest way that can be used for this purpose: https://docs.rs/rustracing_jaeger/0.1.8/rustracing_jaeger/span/index.html#how-to-injectextract-a-span

**Comment by bpmason1** [comment]
My logic is 
```
    let (tracer, span_rx) = Tracer::new(AllSampler);
    {
        let mut carrier: HashMap<String, String> = HashMap::new();
        for hv in Headers::take_from(&mut state).iter() {
            info!("{} -> {}", hv.name().to_string(), hv.value_string());
            carrier.insert(hv.name().to_string(), hv.value_string());
        }

        let context = SpanContext::extract_from_text_map(&carrier).unwrap();
        let _span = tracer.span("My Endpoint").child_of(&context).start();
        // do cool stuff here
    }
    reporter.report(&span_rx.try_iter().collect::<Vec<_>>())
```
I see the traces appearing in the Jaeger dashboard but the traces are not associated with the span of the external application that sent the request.

I have verified that the header data that is being added to the HashMap include the `Uber-Trace-Id` header.  Any suggestions on what I am doing wrong?

**Comment by sile** [comment]
I'm not sure, but it may be due to the difference in encoding logic of TraceId or SpanId between `rustracing_jaeger` and the client library you used.
Could you tell me the name and the version of the client library?

**Comment by bpmason1** [comment]
I'm not sure which library you're referring to, but these are all the libraries I use (from my Cargo.toml)
```
chrono = "0.4.6"
dotenv = "0.13.0"
futures = "0.1.25"
gotham = "0.2.1"
gotham_derive = "0.2.1"
hyper = "0.11.27"
jsonwebtoken = "4.0.1"
log = "0.4.6"
log4rs = "0.8.1"
mime = "0.3.12"
rustracing = "0.1.7"
rustracing_jaeger = "0.1.7"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.32"
time = "0.1.40"
trackable = "0.2.20"
```

**Comment by sile** [comment]
Hmm, I guessed that you have used a library other than `rustracing_jaeger` for injecting trace information in HTTP client side, but is it different?

In other words, who is the client that send HTTP requests that contain tracing header? (or who generates tracing headers?)

**Comment by bpmason1** [comment]
The rust application is receiving an HTTP request from a golang application.  The golang application is using `github.com/opentracing/opentracing-go` and `github.com/uber/jaeger-client-go`.  Spans from the golang applilcation have been successfully extract by other services written golang as well as javascript and scala.

**Comment by sile** [comment]
Thank you for your information. I will investigate this issue within a week.

**Comment by sile** [comment]
I investigated this problem.
Perhaps, the cause is that `rustracing_jaeger` assumes all keys of HTTP header fields are lowercase (but your HTTP client have sent a header field named `Uber-Trace-Id`).

For historical reasons, it is difficult to make `extract_from_text_map` method case-insensitive, but there are countermeasures as below:

- (a) Convert keys to lowercase in advance(e.g., `carrier.insert(hv.name().to_lowercase(), hv.value_string())`)
- (b) Update `rustracing_jaeger` to v0.1.9 and use `SpanContext::extract_from_http_header` method instead (it is case-insensitive; an example is [here](https://github.com/sile/rustracing_jaeger/blob/0.1.9/examples/http_hello_server.rs#L37)).

**Comment by bpmason1** [comment]
the upgrade to `rustracing_jaeger` v0.1.9 and `SpanContext::extract_from_http_header` fixed my problem.  Thanks for the prompt response and the awesome project!

**Comment by sile** [comment]
:+1:
