### ISSUE TITLE
Sampled bit from Jaeger is not respected

### ISSUE THREAD

**Issue by bobrik** [sile/rustracing#7]
I'm extracting parent context from an incoming request and can see that `SpanContextState` from `rustracing_jaeger` crate has `is_sampled() = true`. However, the span that I start with the context containing this state does not carry this piece of information.

It looks like span context is not take into account when rustracing decides on whether to sample request or not. I think it should respect downstream decision.

**Comment by sile** [comment]
Thank you for you question.
If I remember correctly, the span sampling policy of a tracer depends on the [sampler](https://docs.rs/rustracing/0.4.0/rustracing/sampler/trait.Sampler.html) implementation. I think that you can use [PassiveSampler](https://docs.rs/rustracing/0.4.0/rustracing/sampler/struct.PassiveSampler.html) to take a parent context into account (and the sampler can be combined with other sampler by using [OrSampler](https://docs.rs/rustracing/0.4.0/rustracing/sampler/struct.OrSampler.html)).
Please let me know if I misunderstand your intentions.

**Comment by bobrik** [comment]
Passive sampler is exactly what I needed! Thanks!

**Comment by sile** [comment]
😄
